# Generated by Django 2.2.7 on 2019-12-17 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eno', models.IntegerField()),
                ('ename', models.CharField(max_length=200)),
                ('esal', models.FloatField()),
                ('eaddr', models.CharField(max_length=300)),
            ],
        ),
    ]
